#ifndef MENU_H_INCLUDED
#define MENU_H_INCLUDED

void menu_Administrador(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES DE ELECCION ENTRE LOS TIPOS DE ADMINISTRADORES
void menu_Control_Parcial(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES QUE CORRESPONDEN AL ADMINISTRADOR SECUNDARIO
void menu_Control_Total(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES QUE CORRESPONDEN AL ADMINISTRADOR PRINCIPAL
void menu_Juego(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES DEL JUEGO
void menu_Modificacion_Puntaje(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES DE MODIFICACION DEL PUNTAJE DEL USUARIO
void menu_Modificacion_Usuario(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES DE MODIFICACION DEL USUARIO
void menu_Modificaciones_Selector(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES SOBRE LO QUE SE DESEA MODIFICAR
void menu_Principal(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES PARA INICIAR COMO ADMINISTRADOR O COMO USUARIO
void menu_Usuario(int x, int y);///FUNCION QUE ORGANIZA EN UN MENU LAS OPCIONES DE INICIO DE SESION Y LA OPCION DE REGISTRO DE UN USUARIO

#endif // MENU_H_INCLUDED



